language: node_js
node_js:
  - "9"
install:
  - npm install typescript -g
  - npm install
script:
  - "(cd src/backend && tsc)"
  - "(cd src/frontend/common && tsc)"
  - "(cd src/frontend/index-member && tsc)"
